export const formats = {
  androidColors: /** @type {'android/colors'} */ ('android/colors'),
  androidDimens: /** @type {'android/dimens'} */ ('android/dimens'),
  androidFontDimens: /** @type {'android/fontDimens'} */ ('android/fontDimens'),
  androidIntegers: /** @type {'android/integers'} */ ('android/integers'),
  androidResources: /** @type {'android/resources'} */ ('android/resources'),
  androidStrings: /** @type {'android/strings'} */ ('android/strings'),
  composeObject: /** @type {'compose/object'} */ ('compose/object'),
  cssVariables: /** @type {'css/variables'} */ ('css/variables'),
  cssFonts: /** @type {'css/fonts.css'} */ ('css/fonts.css'),
  flutterClassDart: /** @type {'flutter/class.dart'} */ ('flutter/class.dart'),
  iosColorsH: /** @type {'ios/colors.h'} */ ('ios/colors.h'),
  iosColorsM: /** @type {'ios/colors.m'} */ ('ios/colors.m'),
  iosMacros: /** @type {'ios/macros'} */ ('ios/macros'),
  iosPlist: /** @type {'ios/plist'} */ ('ios/plist'),
  iosSingletonH: /** @type {'ios/singleton.h'} */ ('ios/singleton.h'),
  iosSingletonM: /** @type {'ios/singleton.m'} */ ('ios/singleton.m'),
  iosStaticH: /** @type {'ios/static.h'} */ ('ios/static.h'),
  iosStaticM: /** @type {'ios/static.m'} */ ('ios/static.m'),
  iosStringsH: /** @type {'ios/strings.h'} */ ('ios/strings.h'),
  iosStringsM: /** @type {'ios/strings.m'} */ ('ios/strings.m'),
  iosSwiftAnySwift: /** @type {'ios-swift/any.swift'} */ ('ios-swift/any.swift'),
  iosSwiftClassSwift: /** @type {'ios-swift/class.swift'} */ ('ios-swift/class.swift'),
  iosSwiftEnumSwift: /** @type {'ios-swift/enum.swift'} */ ('ios-swift/enum.swift'),
  javascriptEs6: /** @type {'javascript/es6'} */ ('javascript/es6'),
  javascriptEsm: /** @type {'javascript/esm'} */ ('javascript/esm'),
  javascriptModule: /** @type {'javascript/module'} */ ('javascript/module'),
  javascriptModuleFlat: /** @type {'javascript/module-flat'} */ ('javascript/module-flat'),
  javascriptObject: /** @type {'javascript/object'} */ ('javascript/object'),
  javascriptUmd: /** @type {'javascript/umd'} */ ('javascript/umd'),
  json: /** @type {'json'} */ ('json'),
  jsonAsset: /** @type {'json/asset'} */ ('json/asset'),
  jsonNested: /** @type {'json/nested'} */ ('json/nested'),
  jsonFlat: /** @type {'json/flat'} */ ('json/flat'),
  sketchPalette: /** @type {'sketchPalette'} */ ('sketchPalette'),
  sketchPaletteV2: /** @type {'sketch/palette/v2'} */ ('sketch/palette/v2'),
  lessIcons: /** @type {'less/icons'} */ ('less/icons'),
  lessVariables: /** @type {'less/variables'} */ ('less/variables'),
  scssIcons: /** @type {'scss/icons'} */ ('scss/icons'),
  scssMapDeep: /** @type {'scss/map-deep'} */ ('scss/map-deep'),
  scssMapFlat: /** @type {'scss/map-flat'} */ ('scss/map-flat'),
  scssVariables: /** @type {'scss/variables'} */ ('scss/variables'),
  stylusVariables: /** @type {'stylus/variables'} */ ('stylus/variables'),
  typescriptEs6Declarations: /** @type {'typescript/es6-declarations'} */ (
    'typescript/es6-declarations'
  ),
  typescriptModuleDeclarations: /** @type {'typescript/module-declarations'} */ (
    'typescript/module-declarations'
  ),
};
