export const transformGroups = {
  web: /** @type {'web'} */ ('web'),
  js: /** @type {'js'} */ ('js'),
  scss: /** @type {'scss'} */ ('scss'),
  css: /** @type {'css'} */ ('css'),
  less: /** @type {'less'} */ ('less'),
  html: /** @type {'html'} */ ('html'),
  android: /** @type {'android'} */ ('android'),
  compose: /** @type {'compose'} */ ('compose'),
  ios: /** @type {'ios'} */ ('ios'),
  iosSwift: /** @type {'ios-swift'} */ ('ios-swift'),
  iosSwiftSeparate: /** @type {'ios-swift-separate'} */ ('ios-swift-separate'),
  assets: /** @type {'assets'} */ ('assets'),
  flutter: /** @type {'flutter'} */ ('flutter'),
  flutterSeparate: /** @type {'flutter-separate'} */ ('flutter-separate'),
  reactNative: /** @type {'react-native'} */ ('react-native'),
};
