/* @web/test-runner snapshot v1 */
export const snapshots = {};

snapshots["integration name collisions should warn users of name collisions for flat files"] = 
`⚠️ __integration__/build/variables.css
While building variables.css, token collisions were found; output may be unexpected. Ignore this warning if intentional.
Output name red was generated by:
color.red   #f00
color.background.red   #f00
This many-to-one issue is usually caused by some combination of:
* conflicting or similar paths/names in token definitions
* platform transforms/transformGroups affecting names, especially when removing specificity
* overly inclusive file filters`;
/* end snapshot integration name collisions should warn users of name collisions for flat files */

snapshots["integration name collisions should warn users of name collisions for flat files, brief version"] = 
`⚠️ __integration__/build/variables.css
While building variables.css, token collisions were found; output may be unexpected. Ignore this warning if intentional.

Use log.verbosity "verbose" or use CLI option --verbose for more details.`;
/* end snapshot integration name collisions should warn users of name collisions for flat files, brief version */

